### PR TITLE
Neo4j multihop support

### LINKED ISSUE #5994: Neo4j getLineage with multi-hop support
**Describe the bug**
DataHub is not fully integrated with Neo4j as it does not support multi-hop queries.

We need an implementation of getLineage for Neo4jGraphService, and then we can also set supportsMultiHop() to return true.

**To Reproduce**
1. Set up an instance of DataHub with Neo4j as the Graph Index implementation
2. Ingest some Datasets with lineage to each other.
3. Open the DataHub UI and navigate to a dataset with some lineage.
4. Go to the Impact tab (if using Neo4j this will be disabled).

**Expected behavior**
The expectation is the Lineage tab and "Impact Analysis" should be functional once the Neo4j multi-hop integration is complete.

The following code needs to be implemented or amended in https://github.com/datahub-project/datahub/blob/master/metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:

The getLineage method needs to be implemented for multiple hops in Neo4jGraphService: https://github.com/datahub-project/datahub/blob/2dfc166bbde4f5ae6de04482fd1fcca9dcc3cabc/metadata-io/src/main/java/com/linkedin/metadata/graph/GraphService.java#L94

The supportsMultiHop method should return true for Neo4j: https://github.com/datahub-project/datahub/blob/2dfc166bbde4f5ae6de04482fd1fcca9dcc3cabc/metadata-io/src/main/java/com/linkedin/metadata/graph/GraphService.java#L188

**Screenshots**
Example Lineage tab: https://demo.datahubproject.io/dataset/urn:li:dataset:(urn:li:dataPlatform:looker,long_tail_companions.view.instruction_set,PROD)/Lineage?filter_degree=1&page=1

### PR DESCRIPTION
**Pull request by djordje-mijatovic**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

resolves #5994

### CODE REVIEW

File: metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java [hunk 1]
```diff
@@ -153,4 +162,45 @@ public void testConcurrentRemoveNodes() {
...
+    assertEquals(relationships.get(datasetOneUrn).getDegree().intValue(), 2);
+    assertTrue(relationships.containsKey(datasetTwoUrn));
+    assertEquals(relationships.get(datasetTwoUrn).getDegree().intValue(), 1);
+    assertTrue(relationships.containsKey(dataJobOneUrn));
+    assertEquals(relationships.get(dataJobOneUrn).getDegree().intValue(), 1);
+
+    downstreamLineage = service.getLineage(datasetThreeUrn, LineageDirection.DOWNSTREAM, 0, 1000, 2);
+    assertEquals(downstreamLineage.getTotal().intValue(), 0);
+    assertEquals(downstreamLineage.getRelationships().size(), 0);
+  }
```
Comment (gabe-lyons) [inline metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java:205]: can you move this test into `GraphServiceTestBase.java`? This way we can make sure not to break both graph services as we make changes

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 2]
```diff
@@ -93,6 +105,63 @@ public void addEdge(@Nonnull final Edge edge) {
...
+  @Override
+  public EntityLineageResult getLineage(@Nonnull Urn entityUrn, @Nonnull LineageDirection direction,
+                                        GraphFilters graphFilters, int offset, int count, int maxHops) {
+    log.debug(String.format("Neo4j getLineage maxHops = %d", maxHops));
+
+    final String multiHopTemplate = "MATCH (a {urn: '%s'})-[r:%s*1..%d]->(b) WHERE b:%s RETURN a,r,b"
+            + " UNION "
+            + "MATCH (a {urn: '%s'})<-[r:%s*1..%d]-(b) WHERE b:%s RETURN a,r,b";
+
+    final String directRelationTypes = "DownstreamOf|HasOwner|KnowsUser|Consumes";
```
Comment (gabe-lyons) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:118]: so, this information should now be found in the lineage registry rather than being hardcoded

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 3]
```diff
@@ -93,6 +105,63 @@ public void addEdge(@Nonnull final Edge edge) {
...
+    final String invertedRelationTypes = "Produces";
```
Comment (gabe-lyons) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:119]: same here ^

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 4]
```diff
@@ -93,6 +105,63 @@ public void addEdge(@Nonnull final Edge edge) {
...
+      String relationType = ((InternalRelationship) item.get(1).asList().get(0)).type();
+      int numHops = item.get(1).size();
+      try {
+        relations.add(new LineageRelationship()
+                        .setEntity(Urn.createFromString(urn))
+                        .setType(relationType)
+                        .setDegree(numHops));
+      } catch (URISyntaxException ignored) {
+        log.warn(String.format("Can't convert urn = %s, Error = %s", urn, ignored.getMessage()));
+      }
```
Comment (gabe-lyons) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:153]: its seems like theres some overlap here in executing queries and in the other method- I would consider refactoring before merging.

File: metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java (hunk 1 above)
Comment (djordje-mijatovic) [reply metadata-io/src/test/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphServiceTest.java]: I have removed it from Neo4 tests and also From ElasticSearch tests.

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java (hunk 4 above)
Comment (djordje-mijatovic) [reply metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java]: I couldn't find any overlapping but I anyway split the function as it was too long.

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 5]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+  public EntityLineageResult getLineage(@Nonnull Urn entityUrn, @Nonnull LineageDirection direction,
+                                        GraphFilters graphFilters, int offset, int count, int maxHops) {
+    log.debug(String.format("Neo4j getLineage maxHops = %d", maxHops));
+
+    final String statement = generateLineageStatement(entityUrn, direction, graphFilters, maxHops);
+
+    List<Record> neo4jResult = statement != null ? runQuery(buildStatement(statement, new HashMap<>())).list() : new ArrayList<>();
+
+    neo4jResult = neo4jResult.stream()
+            .collect(Collectors.toMap(item -> item.values().get(2).asNode().get("urn").asString(),
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:120]: Is the "get(2)" safe here? Expecting the item.values array to _always_ have more than one item?

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 6]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+                    Function.identity(),
+                    (item1, item2) -> item1.get(1).size() < item2.get(1).size() ? item1 : item2))
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:122]: This code is slightly challenging to understand

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 7]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+  @Override
+  public EntityLineageResult getLineage(@Nonnull Urn entityUrn, @Nonnull LineageDirection direction,
+                                        GraphFilters graphFilters, int offset, int count, int maxHops) {
+    log.debug(String.format("Neo4j getLineage maxHops = %d", maxHops));
+
+    final String statement = generateLineageStatement(entityUrn, direction, graphFilters, maxHops);
+
+    List<Record> neo4jResult = statement != null ? runQuery(buildStatement(statement, new HashMap<>())).list() : new ArrayList<>();
+
+    neo4jResult = neo4jResult.stream()
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:119]: It would be nice to have a comment explaining what the following stream logic is doing.

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 8]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+            .collect(Collectors.toMap(item -> item.values().get(2).asNode().get("urn").asString(),
+                    Function.identity(),
+                    (item1, item2) -> item1.get(1).size() < item2.get(1).size() ? item1 : item2))
+            .values()
+            .stream()
+            .collect(Collectors.toList());
+
+    LineageRelationshipArray relations = new LineageRelationshipArray();
+    neo4jResult.stream()
+            .skip(offset).limit(offset + count)
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:129]: Minor: are we sure that limit doesnt just accept count?

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 9]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+    final String allowedEntityTypes = String.join(" OR b:", graphFilters.getAllowedEntityTypes());
+
+    final String statementDirect = String.format(multiHopTemplateDirect, entityUrn, upstreamRel, maxHops, allowedEntityTypes);
+    final String statementIndirect = String.format(multiHopTemplateIndirect, entityUrn, dowStreamRel, maxHops, allowedEntityTypes);
+
+    String statement = null;
+    if (upstreamRel.length() > 0 && dowStreamRel.length() > 0) {
+      statement = statementDirect + " UNION " + statementIndirect;
+    } else {
+      if (upstreamRel.length() > 0) {
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:178]: Minor: these nested statements can be brought up a level as `else if `

File: metadata-io/src/test/java/com/linkedin/metadata/graph/dgraph/DgraphGraphServiceTest.java [hunk 10]
```diff
@@ -784,4 +784,9 @@ public void testGetDestinationUrnsFromResponseData() {
                 RELATED_ENTITY_COMPARATOR
         );
     }
+
+    @Override
+    public void testPopulatedGraphServiceGetLineageMultihop() {
+        // TODO: Remove this overridden method once the multihop for dGraph is implemented!
```
Comment (jjoyce0510) [inline metadata-io/src/test/java/com/linkedin/metadata/graph/dgraph/DgraphGraphServiceTest.java:790]: Thanks!

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java (hunk 4 above)
Comment (jjoyce0510) [reply metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java]: Love splitting methods :-)

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java (hunk 8 above)
Comment (djordje-mijatovic) [reply metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:129]: You are right.

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java (hunk 5 above)
Comment (djordje-mijatovic) [reply metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:120]: Yes. The query returns array of 3 elements: start node, end node and relation.

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 11]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+                relations.add(new LineageRelationship()
+                        .setEntity(Urn.createFromString(urn))
+                        .setType(relationType)
+                        .setDegree(numHops));
+              } catch (URISyntaxException ignored) {
+                log.warn(String.format("Can't convert urn = %s, Error = %s", urn, ignored.getMessage()));
+              }
+            });
+
+    EntityLineageResult result = new EntityLineageResult().setStart(offset)
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:147]: Minor formatting:

```
new EntityLineageResult()
    .setStart(offset) 
```

File: metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java [hunk 12]
```diff
@@ -94,6 +106,85 @@ public void addEdge(@Nonnull final Edge edge) {
...
+            .map(item -> item.getType())
+            .collect(Collectors.joining("|"));
+
+    final String allowedEntityTypes = String.join(" OR b:", graphFilters.getAllowedEntityTypes());
+
+    final String statementDirect = String.format(multiHopTemplateDirect, entityUrn, upstreamRel, maxHops, allowedEntityTypes);
+    final String statementIndirect = String.format(multiHopTemplateIndirect, entityUrn, dowStreamRel, maxHops, allowedEntityTypes);
+
+    String statement = null;
+    if (upstreamRel.length() > 0 && dowStreamRel.length() > 0) {
```
Comment (jjoyce0510) [inline metadata-io/src/main/java/com/linkedin/metadata/graph/neo4j/Neo4jGraphService.java:178]: naming nit: dowStreamRel -> downStreamRel

File: metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java [hunk 13]
```diff
@@ -1583,4 +1583,45 @@ public void run() {
...
+      assertTrue(relationships.containsKey(datasetOneUrn));
+      assertEquals(relationships.get(datasetOneUrn).getDegree().intValue(), 2);
+      assertTrue(relationships.containsKey(datasetTwoUrn));
+      assertEquals(relationships.get(datasetTwoUrn).getDegree().intValue(), 1);
+      assertTrue(relationships.containsKey(dataJobOneUrn));
+      assertEquals(relationships.get(dataJobOneUrn).getDegree().intValue(), 1);
+
+      downstreamLineage = service.getLineage(datasetThreeUrn, LineageDirection.DOWNSTREAM, 0, 1000, 2);
+      assertEquals(downstreamLineage.getTotal().intValue(), 0);
+      assertEquals(downstreamLineage.getRelationships().size(), 0);
```
Comment (jjoyce0510) [inline metadata-io/src/test/java/com/linkedin/metadata/graph/GraphServiceTestBase.java:1625]: Nice test.

Any cases for when there are _no_ downstream or upstream edges for the source urn?

File: metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/ElasticSearchGraphServiceTest.java [hunk 14]
```diff
@@ -208,45 +201,4 @@ public void testConcurrentRemoveNodes() {
     // https://github.com/datahub-project/datahub/issues/3118
     throw new SkipException("ElasticSearchGraphService produces duplicates");
   }
-
-  @Test
-  public void testPopulatedGraphServiceGetLineageMultihop() throws Exception {
```
Comment (jjoyce0510) [inline metadata-io/src/test/java/com/linkedin/metadata/graph/elastic/ElasticSearchGraphServiceTest.java:213]: Why are we removing this test for elastic search?

**Comment by jjoyce0510** [comment]
Most important piece is around removing tests. Ready to submit as soon as I hear back

**Review by jjoyce0510 — APPROVED** [review]
LGTM! Thank you
